### ISSUE TITLE
Update the corpora to quanteda v2 and improve documentation

### ISSUE THREAD

**Issue by stefan-mueller** [quanteda/quanteda.corpora#9]
The corpora should be updated to the structure of the **quanteda** corpus v2 soon (probably after the next CRAN release), We should also aim for a consistent documentation of the corpora. This includes
-  a short description of the corpus object
- `@format`: a list of all document-level variables and a short description of each variable
- `@source`: link/reference to source of corpus
- `@reference`: reference to paper/data repository (if applicable)

**Comment by kbenoit** [comment]
Yes this is issue #1624 and already underway in `dev-v2-newcorpusdata` to be merged into `dev-v2`.

True that `data_corpus_irishbudget2010` and `data_corpus_dailnoconf1991` could get a better format section (similar to `data_corpus_inaugural`), but the rest of what you describe is all already there.

The last thing we want to do is describe the internal structure of the corpus object. I've had to issue PRs for four other packages who insisted on addressing the corpus internals directly instead of using our functions! 😠

**Comment by kbenoit** [comment]
Ah sorry, I just saw that is **quanteda.corporda**!  Totally agree that we should do this. It will be an interesting question however as to what happens when new formats are loaded into an old version of **quanteda**. Since the version will automatically upgrade them, we probably want to upgrade the companion data packages with a considerable lag.

**Comment by stefan-mueller** [comment]
I agree with your comments. In that case, I will only improve the documentation in the way described above, but will not upgrade the corpus format for the **quanteda.corpora** objects (yet). Just let me know whether following the conventions in #8 is what you have in mind or whether we should add more/different information.

**Comment by stefan-mueller** [comment]
The documentation was improved in #8, but I do not close this issue because in the medium/long term we might need to upgrade the corpus format.
